version: "3.6"

services:
  report-service:
    healthcheck:
      test: curl -f http://localhost:8080/monitoring/health | grep -io '^{"status":"UP"' || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 300s
